### ISSUE TITLE
Publish on Deno JSR

### ISSUE THREAD

**Issue by Sovenok-Hacker** [grammyjs/grammY#726] opened 2024-12-18 19:38 UTC
I think it would be good.

**Comment by KnorpelSenf** [comment] 2024-12-18 19:44
Please search for existing issues before opening new ones. This is a duplicate of #559. Publishing to JSR is planned. Publishing there is currently actually still a really hard problem (check the existing issue for details), but we are going to crack it at some point. Closing as duplicate.

**Closed by KnorpelSenf** 2024-12-18 19:44 UTC
