### ISSUE TITLE
403: Forbidden: bot is not a member of the channel chat

### ISSUE THREAD

**Issue by mrogx** [grammyjs/grammY#309] opened 2022-11-08 10:00 UTC
On the event 'my_chat_member' (when the bot is added to a channel. NOT a group/supergroup), sometimes (~50% chance), when a this.bot.api.ANY_FUNCTION_HERE that has to get something from that channel is called, results in an error '403: Forbidden: bot is not a member of the channel chat'. The bot is actually a member of that channel with all the necessary right enabled.

Eg:
```
{
  "stack": "GrammyError: Call to 'getChatAdministrators' failed! (403: Forbidden: bot is not a member of the channel chat)\n    at toGrammyError (/root/node/mob4/node_modules/grammy/out/core/error.js:35:12)\n    at ApiClient.callApi (/root/node/mob4/node_modules/grammy/out/core/client.js:86:48)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Service.getAdmins (/root/telegram/telegram.js:1539:11)\n    at async Service.isOwner (/root/telegram/telegram.js:1557:18)\n    at async Service.registerStart (/root/telegram/telegram.js:466:24)",
  "message": "Call to 'getChatAdministrators' failed! (403: Forbidden: bot is not a member of the channel chat)"
}
```

Only workaround, after this happens, is to remove the bot from the channel and add it again (and hope I does not happen again).

**Comment by KnorpelSenf** [comment] 2022-11-09 00:24
This sounds like a bug in your code. You need to provide more information if you are looking for help to fix the problem.

**Comment by mrogx** [comment] 2022-11-09 10:37
@KnorpelSenf  I've created a new stripped down version of my project and managed to reproduce the issue on it.

grammy@1.12.0

```
const { Bot } = require("grammy")

const TEST = {
    start() {
        console.log('Started!')
		this.bot = new Bot('BOT_TOKEN_HERE')
		this.bot.start()
		this.registerCommands()
	},
    registerCommands() {
		this
		.contextMyChatMember()
	},
    contextMyChatMember() {
		this.bot.on('my_chat_member', (ctx) => {
			try {
				this.registerStart(ctx)
			} catch (err) {
				console.log(err)
			}
		})
		return this
	},
    async registerStart (ctx, external) {
		ctx.webhookReply = false
		if (!ctx.update.my_chat_member.from.is_bot) {
			if (ctx.update.my_chat_member.new_chat_member.status !== "kicked" && ctx.update.my_chat_member.new_chat_member.status !== "left") {
				const checkOwner = await this.isTUIDOwner(ctx.from.id, ctx.chat.id)
				if (!checkOwner) return false
			}
		}
	},
    async isTUIDOwner(tuid, cid) {
		const admins = await this.getAdmins(cid)
		if (!admins) {
			this.removeBot(cid)
			return false
		}
		for (const admin of admins) {
			if (admin.user.id === tuid && admin.status === 'creator') return true
		}
		this.queueMessage(tuid, 'This bot can only be added by the channel\'s owner.')
		this.removeBot(cid)
		return false
	},
    async getAdmins(cid) {
		try {
			return await this.bot.api.getChatAdministrators(Number(cid))
		} catch (err) {
			console.log(err)
			return false
		}
	},
    async removeBot(chat) {
		try {
			return await this.bot.api.leaveChat(Number(chat))
		} catch (err) {
			console.log(err)
			return false
		}
	}
}

TEST.start()
```

Console:

```
node index.js
Started!
GrammyError: Call to 'getChatAdministrators' failed! (403: Forbidden: bot is not a member of the channel chat)
    at toGrammyError (/root/node/test/node_modules/grammy/out/core/error.js:35:12)
    at ApiClient.callApi (/root/node/test/node_modules/grammy/out/core/client.js:86:48)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.getAdmins (/root/node/test/index.js:48:11)
    at async Object.isTUIDOwner (/root/node/test/index.js:34:18)
    at async Object.registerStart (/root/node/test/index.js:28:24) {
  method: 'getChatAdministrators',
  payload: { chat_id: -1001878159275 },
  ok: false,
  error_code: 403,
  description: 'Forbidden: bot is not a member of the channel chat',
  parameters: {}
}
GrammyError: Call to 'leaveChat' failed! (403: Forbidden: bot is not a member of the channel chat)
    at toGrammyError (/root/node/test/node_modules/grammy/out/core/error.js:35:12)
    at ApiClient.callApi (/root/node/test/node_modules/grammy/out/core/client.js:86:48)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.removeBot (/root/node/test/index.js:56:11) {
  method: 'leaveChat',
  payload: { chat_id: -1001878159275 },
  ok: false,
  error_code: 403,
  description: 'Forbidden: bot is not a member of the channel chat',
  parameters: {}
}
```

**Comment by KnorpelSenf** [comment] 2022-11-09 20:29
This is a bug in your code. The error can happen if your bot is not a member of the channel when you call the respective methods. For example, you can add the bot to the channel, remove the bot from the channel, unban the bot from the channel, and then run the above script. In that case, the bot will receive an old update about being added to the channel, while it in fact already was removed und unblocked again. There is not much you can do in this case, apart from handling and logging the error.

Check out the docs about error handling to do this: https://grammy.dev/guide/errors.html

**Comment by mrogx** [comment] 2022-11-11 01:02
The above errors happens using these steps:

1. Create a new private channel
2. Add the bot
3. Make it an admin (just use the default rights)

How is this an error in my code?

**Comment by KnorpelSenf** [comment] 2022-11-11 06:33
I cannot reproduce it the way you described, even not after going through these steps 10 times.

Note that this error is thrown by Telegram. It does not depend on the library performing the network calls whether or not you're running into this issue.

Even then, network calls might fail, for example through the above condition of delayed updates. You must be able to handle errors correctly.

**Comment by mrogx** [comment] 2022-11-15 05:55
@KnorpelSenf You are right, it seems to be an issue with Telegram. I managed to reproduce it on telegraf as well. I've also manually called the Telegram API with the same results.

I logged the events and responses, if anyone is curious:
```
getUpdates
{
  offset: 1,
  limit: undefined,
  timeout: 30,
  allowed_updates: undefined
}
{
  "ok": true,
  "result": [
    {
      "update_id": <removed_for_security_reasons>,
      "my_chat_member": {
        "chat": {
          "id": -1001659392243,
          "title": "sgfdhfdfghdf",
          "type": "channel"
        },
        "from": {
          "id": <removed_for_security_reasons>,
          "is_bot": false,
          "first_name": "<removed_for_security_reasons>",
          "last_name": "<removed_for_security_reasons>",
          "username": "<removed_for_security_reasons>",
          "language_code": "en"
        },
        "date": 1668489762,
        "old_chat_member": {
          "user": {
            "id": <removed_for_security_reasons>,
            "is_bot": true,
            "first_name": "<removed_for_security_reasons>",
            "username": "<removed_for_security_reasons>"
          },
          "status": "left"
        },
        "new_chat_member": {
          "user": {
            "id": <removed_for_security_reasons>,
            "is_bot": true,
            "first_name": "<removed_for_security_reasons>",
            "username": "<removed_for_security_reasons>"
          },
          "status": "administrator",
          "can_be_edited": false,
          "can_manage_chat": true,
          "can_change_info": true,
          "can_post_messages": true,
          "can_edit_messages": true,
          "can_delete_messages": true,
          "can_invite_users": true,
          "can_restrict_members": true,
          "can_promote_members": false,
          "can_manage_video_chats": true,
          "is_anonymous": false,
          "can_manage_voice_chats": true
        }
      }
    }
  ]
}

getChatAdministrators
{ chat_id: -1001659392243 }
{
  ok: false,
  error_code: 403,
  description: 'Forbidden: bot is not a member of the channel chat'
}
```

**Comment by KnorpelSenf** [comment] 2022-11-21 00:54
In that case you should open an issue at https://github.com/tdlib/telegram-bot-api. Please include information about how to reproduce the issue by calling the Bot API manually.

This is not an issue with grammY, so I'll close this issue.

**Closed by KnorpelSenf** 2022-11-21 00:54 UTC
