### ISSUE TITLE
bug: api.getStickerSet returns true

### ISSUE THREAD

**Issue by habdenscrimen** [grammyjs/grammY#199] opened 2022-05-12 09:12 UTC
```ts
const stickerSetName = `my_name`
const stickerSet = await ctx.api.getStickerSet(stickerSetName)

// stickerSet === true
```

This behavior is for valid and invalid set names - it returns `true` in any case.

**Comment by KnorpelSenf** [comment] 2022-05-12 09:37
Did you enable webhookReplies for this method?

**Comment by KnorpelSenf** [comment] 2022-05-12 09:49
I cannot reproduce this.

The following code works for me.
```ts
import { Api } from "https://deno.land/x/grammy@v1.8.3/mod.ts"

const api = new Api("<token>");

const stickerSetName = "senya_animated"
const stickerSet = await api.getStickerSet(stickerSetName)

console.log(stickerSet.stickers.length); // output: 24
```

**Comment by habdenscrimen** [comment] 2022-05-12 09:54
> Are you running on webhooks and did you enable `canUseWebhookReply` for this method?

Yes, on webhooks.
And thanks for your quick reply! I disabled `canUseWebhookReply` for this method, and voila!

```ts
canUseWebhookReply: (method) => method !== 'getStickerSet'
```

**Comment by KnorpelSenf** [comment] 2022-05-12 09:57
Glad it's fixed! :)

Also beware of more pitfalls with webhook replies: https://grammy.dev/guide/deployment-types.html#webhook-reply

Closing.

**Closed by KnorpelSenf** 2022-05-12 09:57 UTC
