### ISSUE TITLE
Error handler via `bot.catch()` does not get called.

### ISSUE THREAD

**Issue by magdyamr542** [grammyjs/grammY#269] opened 2022-08-26 10:27 UTC
Hi
We have a problem that the customer error handler used by calling `bot.catch(myErrorHandler)` is not called when a `getUpdates()` throws an error.
Such an error can be the following:  ` Call to 'getUpdates' failed! (409: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running)`.
In your documentation [here](https://grammy.dev/guide/errors.html#catching-errors) you describe how to install a custom error handler but that does not really work. or did i do something wrong ?

The question is **how to access such erros** because currently this does not seem possible.

Here is an example code in **deno** to reproduce the problem. deno version used is `1.25.0`
```typescript
import { Bot } from "https://deno.land/x/grammy/mod.ts";

// Create bot object
const bot1 = new Bot(""); // <-- place your bot token inside this string
const bot2 = new Bot(""); // <-- place the same token here again

const startBot = (bot: Bot, name: string) => {
  console.log(`[${name}] starting`);
  console.log(`[${name}] adding custom error handler`);

  // TODO: this does not get called
  bot.catch((error) => {
    console.log(`[${name}] got error from custom error handler`, error);
  });

  // Listen for messages
  bot.on("message:text", (ctx) => {
    console.log(`[${name}] got text msg`, ctx.message.text);
    ctx.reply(`Reply from ${name}`);
  });

  bot.start();
};

const handleUpdates = async (bot: Bot, name: string) => {
  console.log(`[${name}] getting updates`);
  while (true) {
    try {
      const update = await bot.api.getUpdates();
      console.log(`[${name}] got update`, JSON.stringify(update));
      await new Promise((f) => setTimeout(f, 1000)); // sleep
    } catch (error) {
      // this works fine
      console.error(`[${name}] got error from catch`, error);
    }
  }
}; 

startBot(bot1, "bot1");
startBot(bot2, "bot2");
handleUpdates(bot1, "bot1");
handleUpdates(bot2, "bot2");
```
Run it with `deno run --allow-net --no-check --allow-env index.ts `

Here are the logs i am getting. Notice that the `got error from custom error handler` message is not there indicating the customer error handler is not called.

```
[bot1] starting
[bot1] adding custom error handler
[bot2] starting
[bot2] adding custom error handler
[bot1] getting updates
[bot2] getting updates
[bot2] got update []
[bot1] got error from catch Error: Call to 'getUpdates' failed! (409: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running)
    at ApiClient.callApi (https://deno.land/x/grammy@v1.1.4/core/client.ts:234:19)
    at async handleUpdates (file:///home/name/deno/index.ts:29:22)
[bot1] got update []
[bot2] got error from catch Error: Call to 'getUpdates' failed! (409: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running)
    at ApiClient.callApi (https://deno.land/x/grammy@v1.1.4/core/client.ts:234:19)
    at async handleUpdates (file:///home/name/deno/index.ts:29:22)
```

**Comment by KnorpelSenf** [comment] 2022-08-28 13:41
Telegram does not allow you to poll updates from two places. It makes no sense to handle this error programmatically.

Generally, the errors thrown by `getUpdates` calls can only mean two things:
1. Your code is incorrect. In that case, grammY will crash, so you can fix the problem. It makes no sense to handle this programmatically in userland code.
2. Your code is correct, but there are temporary problems such as network issues, flood waits, server downtime, or internal server errors by Telegram. In all of these cases, grammY will handle the error internally fully automatically according to the specification, and then retry the operation. It makes no sense to handle this any differently in userland code.

**Comment by magdyamr542** [comment] 2022-08-29 07:17
Thanks for your reply. Actually we have a platform where we run bots and we also have 2 deployment stages for this platform. When someone let's say in **staging** uses a bot with a token that is running in **production** we get theses errors and send them per email so someone would fix it and stop one of the bots or use a different token. so we actually make use of these errors.

Is there anything that can be done such that the user of the library gets the internal errors that grammy handles as well ?

**Comment by KnorpelSenf** [comment] 2022-08-29 07:30
Sharing bot tokens between environments is a flawed approach. You may potentially lose some updates that were sent to a bot running in production. In addition, you're actively crashing the instances running on production by doing that. The solution to your problem is to not share bot tokens, which will avoid these errors entirely.

When grammY crashes (case 1 above) the call to `bot.start` will reject. Hence, you could get access to the error like that:

```ts
bot.start()
  .catch((err) => {
      console.log("Houston, we have a bug:", err)
  })
```

When grammY retries a request to `getUpdates` automatically, you won't be able to handle the error.

**Comment by magdyamr542** [comment] 2022-08-29 10:01
We have the linting rule already thanks :) the example i sent is just a small demonstration of why it does not work. I know it's a mistake to share tokens between envs but we can't stop the people using our platform from using such tokens twice. So we need access to such errors. In this example i tried to implement what you suggested by catching the errors on start but it still does not work. I don't get any errors. Funny thing is that i still get replies from both instances at the same time

```
import { Bot } from "https://deno.land/x/grammy/mod.ts";

// Create bot object
const bot1 = new Bot(""); // <-- place your bot token inside this string
const bot2 = new Bot(""); // <-- place the same token here again

const startBot = (bot: Bot, name: string) => {
  console.log(`[${name}] starting`);
  console.log(`[${name}] adding custom error handler`);

  // TODO: this does not get called
  bot.catch((error) => {
    console.log(`[${name}] got error from custom error handler`, error);
  });

  // Listen for messages
  bot.on("message:text", async (ctx) => {
    console.log(`[${name}] got text msg`, ctx.message.text);
    try {
      await ctx.reply(`Reply from ${name}`);
    } catch (error) {
    console.log(`[${name}] got error from ctx.reply`, error);
    }
  });

  bot.start().catch((error) => {
    console.log(`[${name}] error from catch` , error);
  })
};

startBot(bot1, "bot1");
startBot(bot2, "bot2");
```

![Screenshot from 2022-08-29 11-57-01](https://user-images.githubusercontent.com/55108505/187176542-1596bd2d-e3b8-4c8c-b7e5-c26e19df22dd.png)

**Comment by KnorpelSenf** [comment] 2022-08-29 10:06
You cannot rely on this detection. It is a best-effort approach implemented by Telegram. As I said before, it is a bad idea to build any software of top of these errors. Consider adding checks that make sure every token is only used once.

Alternatively, you could use webhooks. They have much less overhead especially in setups that run many bots on the same code. Also, they don't suffer from your current problem.

**Comment by magdyamr542** [comment] 2022-08-29 10:26
Webhooks is on our TODO list. For us there is currently no way to stop people from using the same token twice espicially because there is a seperate database for each environment and people could just use a token in staging that is being used in production. So from what you say there is no way that you at least notify the users of the library that an error happended ? I mean i am sure there are some people who are interested in knowing which errors are happending with their bots right :) ?

**Comment by magdyamr542** [comment] 2022-08-30 20:51
It's not feasible for us to crash because the platform is centered around around the idea of a bot runner. it's also difficult to prevent users from using the same token for their bots because we use two separate environments. i really think it's reasonable if the library users could have some way of getting notified about the internal errors that occur. grammY can still handle the error internally of course but notifying the library users would be also a good idea and it's really simple to implement with an event emitter that emits errors don't you think ?

**Comment by Legiew** [comment] 2022-09-02 20:25
> Sharing bot tokens between environments is a flawed approach. You may potentially lose some updates that were sent to a bot running in production. In addition, you're actively crashing the instances running on production by doing that. The solution to your problem is to not share bot tokens, which will avoid these errors entirely.
> 
> When grammY crashes (case 1 above) the call to `bot.start` will reject. Hence, you could get access to the error like that:
> 
> ```ts
> bot.start()
>   .catch((err) => {
>       console.log("Houston, we have a bug:", err)
>   })
> ```
> 
> When grammY retries a request to `getUpdates` automatically, you won't be able to handle the error.

Hey @KnorpelSenf, is there a way to get the same catch if using the runner package?

**Comment by KnorpelSenf** [comment] 2022-09-04 12:47
> it's really simple to implement

The problem isn't that this is too complex to implement. I don't see the point why we should add any features that encourage bad design.



> is there a way to get the same catch if using the runner package

I believe that the promise `task` on the handle returned by the `run` function will reject, but I haven't tested this because, well, it's just not a good idea to write a bot that way :)

I think there isn't anything else to add to this, so I'll close this issue. If you have any further comments or questions, feel free to leave them here (or reopen)!

**Closed by KnorpelSenf** 2022-09-04 12:47 UTC
